In [1]:
# Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import csv

In [37]:
path = os.path.join("Raw","")
# ITT Storage and Peripheries
LNVGY = pd.read_csv(os.path.join(path, "IT_TechHardwareStorage/LNVGY.csv"))
HPE = pd.read_csv(os.path.join(path, "IT_TechHardwareStorage/HPE.csv"))
DELL = pd.read_csv(os.path.join(path, "IT_TechHardwareStorage/DELL.csv"))

# IT Semiconductors
INTC = pd.read_csv(os.path.join(path, "IT_Semiconductors/INTC.csv"))
QCOM = pd.read_csv(os.path.join(path, "IT_Semiconductors/QCOM.csv"))

# Industrials_AerospaceAndDefence
EADSF = pd.read_csv(os.path.join(path, "Industrials_AerospaceAndDefence/EADSF.csv"))
BA = pd.read_csv(os.path.join(path, "Industrials_AerospaceAndDefence/BA.csv"))

# Consumer Staples - Household
CL = pd.read_csv(os.path.join(path, "ConsumerStaples_Household/CL.csv"))
PG = pd.read_csv(os.path.join(path, "ConsumerStaples_Household/PG.csv"))

# Consumer Staples - Hypermarkets
COST = pd.read_csv(os.path.join(path, "ConsumerStaples_Hypermarkets/COST.csv"))
WMT = pd.read_csv(os.path.join(path, "ConsumerStaples_Hypermarkets/WMT.csv"))

# Consumer Staples - Soft Drinks
PEP = pd.read_csv(os.path.join(path, "ConsumerStaples_SoftDrinks/PEP.csv"))
KO = pd.read_csv(os.path.join(path, "ConsumerStaples_SoftDrinks/KO.csv"))

# Industrials Airlines
DAL = pd.read_csv(os.path.join(path, "Industrials_Airlines/DAL.csv"))
UAL = pd.read_csv(os.path.join(path, "Industrials_Airlines/UAL.csv"))
AAL = pd.read_csv(os.path.join(path, "Industrials_Airlines/AAL.csv"))

# Health Care - Pharmaceuticals
PFE = pd.read_csv(os.path.join(path, "HealthCare_Pharmaceuticals/PFE.csv"))
JNJ = pd.read_csv(os.path.join(path, "HealthCare_Pharmaceuticals/JNJ.csv"))

# Communications - Interactive Media
FB = pd.read_csv(os.path.join(path, "Comm_InteractiveMedia/FB.csv"))
GOOGL = pd.read_csv(os.path.join(path, "Comm_InteractiveMedia/GOOGL.csv"))

# Consumer Discretionary - Restaurants
SBUX = pd.read_csv(os.path.join(path, "ConsumerDisc_Restaurants/SBUX.csv"))
MCD = pd.read_csv(os.path.join(path, "ConsumerDisc_Restaurants/MCD.csv"))

# Consumer Discretionary - Automobile
FCAU = pd.read_csv(os.path.join(path, "ConsumerDisc_Auto/FCAU.csv"))
F = pd.read_csv(os.path.join(path, "ConsumerDisc_Auto/F.csv"))
GM = pd.read_csv(os.path.join(path, "ConsumerDisc_Auto/GM.csv"))

# Communications - Telecommunications
TMUS = pd.read_csv(os.path.join(path, "Comm_Telecom/TMUS.csv"))
T = pd.read_csv(os.path.join(path, "Comm_Telecom/T.csv"))

# Energy - Oil & Gas
XOM = pd.read_csv(os.path.join(path, "Energy_OilAndGas/XOM.csv"))
CVX = pd.read_csv(os.path.join(path, "Energy_OilAndGas/CVX.csv"))
 
# Financial Services - Banks
WFC = pd.read_csv(os.path.join(path, "FinancialServices_Banks/WFC.csv"))
BAC = pd.read_csv(os.path.join(path, "FinancialServices_Banks/BAC.csv"))

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-07-01,17.250000,18.480000,16.219999,17.879999,16.320553,1904433600
1,2015-08-01,17.910000,18.070000,14.600000,16.440001,15.006145,2325559300
2,2015-09-01,15.950000,16.480000,15.250000,15.580000,14.221155,1777912500
3,2015-10-01,15.520000,17.440001,14.630000,16.780001,15.365807,1848594500
4,2015-11-01,16.900000,18.090000,16.870001,17.430000,15.961024,1439390500
...,...,...,...,...,...,...,...
56,2020-03-01,28.350000,29.750000,17.950001,21.230000,20.949295,2826499000
57,2020-04-01,19.930000,25.320000,19.510000,24.049999,23.883434,1636882500
58,2020-05-01,23.379999,26.170000,20.100000,24.120001,23.952951,1447546400
59,2020-06-01,24.280001,29.010000,23.680000,24.780001,24.608379,900893000
60,2020-06-15,23.760000,25.170000,23.690001,25.150000,25.150000,76268479